
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.search_results = QtWidgets.QListWidget(self.centralwidget)
        self.search_results.setGeometry(QtCore.QRect(10, 40, 211, 500))
        self.search_results.setObjectName("search_results")
        self.vertical_layout_widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.vertical_layout_widget_2.setGeometry(QtCore.QRect(230, 40, 551, 501))
        self.vertical_layout_widget_2.setObjectName("vertical_layout_widget_2")
        self.vertical_layout_2 = QtWidgets.QVBoxLayout(self.vertical_layout_widget_2)
        self.vertical_layout_2.setContentsMargins(0, 0, 0, 0)
        self.vertical_layout_2.setObjectName("vertical_layout_2")
        self.playlist_window = QtWidgets.QListWidget(self.vertical_layout_widget_2)
        self.playlist_window.setObjectName("playlist_window")
        self.vertical_layout_2.addWidget(self.playlist_window)
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.slider_label_1 = QtWidgets.QLabel(self.vertical_layout_widget_2)
        self.slider_label_1.setObjectName("slider_label_1")
        self.horizontal_layout.addWidget(self.slider_label_1)
        self.slider = QtWidgets.QSlider(self.vertical_layout_widget_2)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontal_layout.addWidget(self.slider)
        self.slider_label_2 = QtWidgets.QLabel(self.vertical_layout_widget_2)
        self.slider_label_2.setObjectName("slider_label_2")
        self.horizontal_layout.addWidget(self.slider_label_2)
        self.vertical_layout_2.addLayout(self.horizontal_layout)
        self.horizontal_layout_3 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_3.setObjectName("horizontal_layout_3")
        self.volume_decrease_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.volume_decrease_button.setObjectName("volume_decrease_button")
        self.horizontal_layout_3.addWidget(self.volume_decrease_button)
        self.play_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.play_button.setObjectName("play_button")
        self.horizontal_layout_3.addWidget(self.play_button)
        self.pause_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.pause_button.setObjectName("pause_button")
        self.horizontal_layout_3.addWidget(self.pause_button)
        self.stop_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.stop_button.setObjectName("stop_button")
        self.horizontal_layout_3.addWidget(self.stop_button)
        self.volume_increase_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.volume_increase_button.setObjectName("volume_increase_button")
        self.horizontal_layout_3.addWidget(self.volume_increase_button)
        self.vertical_layout_2.addLayout(self.horizontal_layout_3)
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        self.prev_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.prev_button.setObjectName("prev_button")
        self.horizontal_layout_2.addWidget(self.prev_button)
        self.next_button = QtWidgets.QPushButton(self.vertical_layout_widget_2)
        self.next_button.setObjectName("next_button")
        self.horizontal_layout_2.addWidget(self.next_button)
        self.vertical_layout_2.addLayout(self.horizontal_layout_2)
        self.enter_yandex_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_yandex_button.setGeometry(QtCore.QRect(435, 10, 151, 22))
        self.enter_yandex_button.setObjectName("enter_yandex_button")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(160, 10, 61, 22))
        self.search_button.setObjectName("search_button")
        self.downloaded_tracks = QtWidgets.QListWidget(self.centralwidget)
        self.downloaded_tracks.setGeometry(QtCore.QRect(790, 40, 211, 500))
        self.downloaded_tracks.setObjectName("downloaded_tracks")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(790, 10, 211, 22))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.slider_label_1.setText(_translate("MainWindow", "0:00"))
        self.slider_label_2.setText(_translate("MainWindow", "0:00"))
        self.volume_decrease_button.setText(_translate("MainWindow", "V (-)"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.volume_increase_button.setText(_translate("MainWindow", "V (+)"))
        self.prev_button.setText(_translate("MainWindow", "Prev Song"))
        self.next_button.setText(_translate("MainWindow", "Next Song"))
        self.enter_yandex_button.setText(_translate("MainWindow", "Вход в Яндекс.Музыка"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Скачанные треки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())