
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 211, 500))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 40, 551, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sliderLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sliderLabel1.setObjectName("sliderLabel1")
        self.horizontalLayout.addWidget(self.sliderLabel1)
        self.slider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.sliderLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sliderLabel2.setObjectName("sliderLabel2")
        self.horizontalLayout.addWidget(self.sliderLabel2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dislikeBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.dislikeBtn.setObjectName("dislikeBtn")
        self.horizontalLayout_4.addWidget(self.dislikeBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.likeBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.likeBtn.setObjectName("likeBtn")
        self.horizontalLayout_4.addWidget(self.likeBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.volumeDescBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.volumeDescBtn.setObjectName("volumeDescBtn")
        self.horizontalLayout_3.addWidget(self.volumeDescBtn)
        self.playBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_3.addWidget(self.playBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_3.addWidget(self.pauseBtn)
        self.stopBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_3.addWidget(self.stopBtn)
        self.volumeIncBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.volumeIncBtn.setObjectName("volumeIncBtn")
        self.horizontalLayout_3.addWidget(self.volumeIncBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalLayout_2.addWidget(self.prevBtn)
        self.nextBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_2.addWidget(self.nextBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.enterYanBtn = QtWidgets.QPushButton(self.centralwidget)
        self.enterYanBtn.setGeometry(QtCore.QRect(629, 10, 151, 22))
        self.enterYanBtn.setObjectName("enterYanBtn")
        self.enterSptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.enterSptBtn.setGeometry(QtCore.QRect(510, 10, 111, 22))
        self.enterSptBtn.setObjectName("enterSptBtn")
        self.Spotify = QtWidgets.QPushButton(self.centralwidget)
        self.Spotify.setGeometry(QtCore.QRect(230, 10, 71, 22))
        self.Spotify.setObjectName("Spotify")
        self.YandexMusic = QtWidgets.QPushButton(self.centralwidget)
        self.YandexMusic.setGeometry(QtCore.QRect(310, 10, 101, 22))
        self.YandexMusic.setObjectName("YandexMusic")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(160, 10, 61, 22))
        self.searchBtn.setObjectName("searchBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sliderLabel1.setText(_translate("MainWindow", "0.00"))
        self.sliderLabel2.setText(_translate("MainWindow", "0.00"))
        self.dislikeBtn.setText(_translate("MainWindow", "Dislike"))
        self.likeBtn.setText(_translate("MainWindow", "Like"))
        self.volumeDescBtn.setText(_translate("MainWindow", "V (-)"))
        self.playBtn.setText(_translate("MainWindow", "Play"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.volumeIncBtn.setText(_translate("MainWindow", "V (+)"))
        self.prevBtn.setText(_translate("MainWindow", "Prev Song"))
        self.nextBtn.setText(_translate("MainWindow", "Next Song"))
        self.enterYanBtn.setText(_translate("MainWindow", "Вход в Яндекс.Музыка"))
        self.enterSptBtn.setText(_translate("MainWindow", "Вход в Spotify"))
        self.Spotify.setText(_translate("MainWindow", "Spotify"))
        self.YandexMusic.setText(_translate("MainWindow", "Яндекс.Музыка"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
